export const testData = {
    expenses: [
      // The following test data is generated by ChatGPT
      // January Expenses
      { date: '2023-01-02', category: 'Dining', description: 'Tim Hortons', amount: 15.00 },
      { date: '2023-01-03', category: 'Fashion', description: 'Roots', amount: 120.00 },
      { date: '2023-01-09', category: 'Entertainment', description: 'Cineplex', amount: 25.00 },
      { date: '2023-01-12', category: 'Groceries', description: 'Loblaw', amount: 90.00 },
      { date: '2023-01-12', category: 'Transportation', description: 'Petro-Canada Gas', amount: 45.00 },
      { date: '2023-01-15', category: 'Utilities', description: 'Hydro One', amount: 65.00 },
      { date: '2023-01-17', category: 'Others', description: 'Amazon.ca Order', amount: 35.00 },
  
      // February Expenses
      { date: '2023-02-02', category: 'Dining', description: 'Swiss Chalet', amount: 50.00 },
      { date: '2023-02-07', category: 'Fashion', description: 'Hudson\'s Bay', amount: 200.00 },
      { date: '2023-02-10', category: 'Entertainment', description: 'Netflix Subscription', amount: 14.99 },
      { date: '2023-02-14', category: 'Groceries', description: 'Metro', amount: 75.00 },
      { date: '2023-02-18', category: 'Transportation', description: 'GO Transit Pass', amount: 120.00 },
      { date: '2023-02-20', category: 'Utilities', description: 'Bell Internet', amount: 80.00 },
      { date: '2023-02-25', category: 'Others', description: 'IKEA Furniture', amount: 250.00 },
  
      // March Expenses
      { date: '2023-03-03', category: 'Dining', description: 'A&W', amount: 25.00 },
      { date: '2023-03-06', category: 'Fashion', description: 'Zara', amount: 150.00 },
      { date: '2023-03-11', category: 'Entertainment', description: 'Spotify Subscription', amount: 9.99 },
      { date: '2023-03-15', category: 'Groceries', description: 'Costco', amount: 300.00 },
      { date: '2023-03-18', category: 'Transportation', description: 'TTC Monthly Pass', amount: 146.25 },
      { date: '2023-03-22', category: 'Utilities', description: 'Enbridge Gas', amount: 60.00 },
      { date: '2023-03-27', category: 'Others', description: 'Canadian Tire Tools', amount: 180.00 },
  
      // April Expenses
      { date: '2023-04-02', category: 'Dining', description: 'Boston Pizza', amount: 55.00 },
      { date: '2023-04-05', category: 'Fashion', description: 'Simons', amount: 140.00 },
      { date: '2023-04-08', category: 'Entertainment', description: 'Amazon Prime Subscription', amount: 7.99 },
      { date: '2023-04-13', category: 'Groceries', description: 'Whole Foods Market', amount: 120.00 },
      { date: '2023-04-17', category: 'Transportation', description: 'Uber', amount: 30.00 },
      { date: '2023-04-21', category: 'Utilities', description: 'Rogers Wireless', amount: 85.00 },
      { date: '2023-04-26', category: 'Others', description: 'Best Buy Electronics', amount: 200.00 },

      // May Expenses
      { date: '2023-05-02', category: 'Dining', description: 'Harvey\'s', amount: 20.00 },
      { date: '2023-05-03', category: 'Fashion', description: 'Gap', amount: 110.00 },
      { date: '2023-05-07', category: 'Entertainment', description: 'Xbox Game Pass', amount: 14.99 },
      { date: '2023-05-12', category: 'Groceries', description: 'No Frills', amount: 65.00 },
      { date: '2023-05-16', category: 'Transportation', description: 'Taxi Fare', amount: 40.00 },
      { date: '2023-05-19', category: 'Utilities', description: 'City Water Bill', amount: 70.00 },
      { date: '2023-05-23', category: 'Others', description: 'IKEA Decor', amount: 150.00 },

      // June Expenses
      { date: '2023-06-02', category: 'Dining', description: 'Subway', amount: 15.00 },
      { date: '2023-06-06', category: 'Fashion', description: 'Old Navy', amount: 90.00 },
      { date: '2023-06-10', category: 'Entertainment', description: 'Bowling Alley', amount: 35.00 },
      { date: '2023-06-14', category: 'Groceries', description: 'Farm Boy', amount: 80.00 },
      { date: '2023-06-17', category: 'Transportation', description: 'Local Bus Pass', amount: 100.00 },
      { date: '2023-06-21', category: 'Utilities', description: 'Natural Gas Bill', amount: 60.00 },
      { date: '2023-06-25', category: 'Others', description: 'Home Hardware', amount: 75.00 },

      // July Expenses
      { date: '2023-07-02', category: 'Dining', description: 'Moxie\'s Grill', amount: 60.00 },
      { date: '2023-07-06', category: 'Fashion', description: 'Club Monaco', amount: 130.00 },
      { date: '2023-07-10', category: 'Entertainment', description: 'Ontario Place Admission', amount: 55.00 },
      { date: '2023-07-14', category: 'Groceries', description: 'Kensington Market Shopping', amount: 80.00 },
      { date: '2023-07-18', category: 'Transportation', description: 'Car Insurance', amount: 120.00 },
      { date: '2023-07-22', category: 'Utilities', description: 'Mobile Phone Bill', amount: 60.00 },
      { date: '2023-07-27', category: 'Others', description: 'Home Depot Tools', amount: 145.00 },
      
      // August Expenses
      { date: '2023-08-03', category: 'Dining', description: 'Jack Astor\'s Bar', amount: 75.00 },
      { date: '2023-08-05', category: 'Fashion', description: 'Nordstrom', amount: 200.00 },
      { date: '2023-08-09', category: 'Entertainment', description: 'Wonderland Tickets', amount: 100.00 },
      { date: '2023-08-13', category: 'Groceries', description: 'Whole Foods', amount: 110.00 },
      { date: '2023-08-17', category: 'Transportation', description: 'Gas Refill', amount: 70.00 },
      { date: '2023-08-21', category: 'Utilities', description: 'Water Bill', amount: 55.00 },
      { date: '2023-08-26', category: 'Others', description: 'Amazon Purchase', amount: 90.00 },


      // September Expenses
      { date: '2023-09-03', category: 'Dining', description: 'Earl\'s Kitchen', amount: 55.00 },
      { date: '2023-09-04', category: 'Fashion', description: 'Banana Republic', amount: 120.00 },
      { date: '2023-09-09', category: 'Entertainment', description: 'Royal Ontario Museum Tickets', amount: 45.00 },
      { date: '2023-09-13', category: 'Groceries', description: 'Trader Joe\'s', amount: 85.00 },
      { date: '2023-09-17', category: 'Transportation', description: 'Parking Fees', amount: 25.00 },
      { date: '2023-09-21', category: 'Utilities', description: 'Waste Management', amount: 50.00 },
      { date: '2023-09-26', category: 'Others', description: 'Prescription Medication', amount: 60.00 },

      // October Expenses
      { date: '2023-10-02', category: 'Dining', description: 'Cheesecake Factory', amount: 70.00 },
      { date: '2023-10-05', category: 'Fashion', description: 'Uniqlo', amount: 100.00 },
      { date: '2023-10-10', category: 'Entertainment', description: 'Movie Theater', amount: 30.00 },
      { date: '2023-10-14', category: 'Groceries', description: 'Farmers Market', amount: 75.00 },
      { date: '2023-10-18', category: 'Transportation', description: 'Ride-Share Service', amount: 40.00 },
      { date: '2023-10-22', category: 'Utilities', description: 'Internet Service', amount: 65.00 },
      { date: '2023-10-27', category: 'Others', description: 'Bookstore Purchase', amount: 35.00 },

      // November Expenses
      { date: '2023-11-02', category: 'Dining', description: 'Starbucks', amount: 30.00 },
      { date: '2023-11-04', category: 'Fashion', description: 'L.L.Bean', amount: 150.00 },
      { date: '2023-11-08', category: 'Entertainment', description: 'Concert Tickets', amount: 90.00 },
      { date: '2023-11-12', category: 'Groceries', description: 'Sobeys', amount: 100.00 },
      { date: '2023-11-16', category: 'Transportation', description: 'Train Ticket', amount: 55.00 },
      { date: '2023-11-20', category: 'Utilities', description: 'Gas Bill', amount: 75.00 },
      { date: '2023-11-24', category: 'Others', description: 'Electronics Repair', amount: 80.00 },

      // December Expenses
      { date: '2023-12-02', category: 'Groceries', description: 'Save on Food', amount: 55.00 },
      { date: '2023-12-02', category: 'Utilities', description: 'Electricity Bill', amount: 75.00 },
      { date: '2023-12-03', category: 'Dining', description: 'Starbucks', amount: 15.00 },
      { date: '2023-12-03', category: 'Transportation', description: 'Train Ticket', amount: 55.00 },
    ].map(e => ({ ...e, type: 'expense' })),

    incomes: [
      // January Income
      { date: '2023-01-05', category: 'Salary', description: 'Monthly Salary from Winners', amount: 2305.00 },
      { date: '2023-01-10', category: 'Interest', description: 'TD Bank Interest', amount: 50.00 },
      { date: '2023-01-15', category: 'Property', description: 'Rental Income', amount: 1250.00 },
      { date: '2023-01-20', category: 'Others', description: 'Gift from Grandma', amount: 100.00 },
  
      // February Income
      { date: '2023-02-05', category: 'Salary', description: 'Monthly Salary from Shopify', amount: 3300.00 },
      { date: '2023-02-10', category: 'Interest', description: 'RBC Interest', amount: 25.00 },
      { date: '2023-02-15', category: 'Property', description: 'Airbnb Income', amount: 500.00 },
      { date: '2023-02-20', category: 'Others', description: 'Tax Refund', amount: 300.00 },
  
      // March Income
      { date: '2023-03-05', category: 'Salary', description: 'Monthly Salary from Telus', amount: 2800.00 },
      { date: '2023-03-10', category: 'Interest', description: 'BMO Savings Interest', amount: 30.00 },
      { date: '2023-03-15', category: 'Property', description: 'Condo Rent', amount: 1500.00 },
      { date: '2023-03-25', category: 'Others', description: 'Lottery Winnings', amount: 200.00 },
    
      // April Income
      { date: '2023-04-05', category: 'Salary', description: 'Monthly Salary from Bank of Montreal', amount: 3000.00 },
      { date: '2023-04-11', category: 'Interest', description: 'High-Interest Savings Account', amount: 20.00 },
      { date: '2023-04-17', category: 'Property', description: 'Office Space Rent', amount: 2000.00 },
      { date: '2023-04-23', category: 'Others', description: 'Birthday Money', amount: 150.00 },

      // May Income
      { date: '2023-05-06', category: 'Salary', description: 'Monthly Salary from Canadian Tire', amount: 2700.00 },
      { date: '2023-05-12', category: 'Interest', description: 'Investment Returns', amount: 35.00 },
      { date: '2023-05-18', category: 'Property', description: 'Summer Cottage Rental', amount: 1200.00 },
      { date: '2023-05-24', category: 'Others', description: 'Freelance Project', amount: 400.00 },

      // June Income
      { date: '2023-06-05', category: 'Salary', description: 'Monthly Salary from Rogers', amount: 2500.00 },
      { date: '2023-06-11', category: 'Interest', description: 'GIC Interest', amount: 50.00 },
      { date: '2023-06-17', category: 'Property', description: 'Parking Space Rent', amount: 300.00 },
      { date: '2023-06-23', category: 'Others', description: 'Online Survey Rewards', amount: 75.00 },

      // July Income
      { date: '2023-07-04', category: 'Salary', description: 'Monthly Salary from Acme Corp', amount: 3200.00 },
      { date: '2023-07-10', category: 'Interest', description: 'Monthly Investment Dividend', amount: 60.00 },
      { date: '2023-07-16', category: 'Property', description: 'Apartment Rental Income', amount: 1500.00 },
      { date: '2023-07-22', category: 'Others', description: 'E-commerce Sales', amount: 480.00 },

      // August Income
      { date: '2023-08-03', category: 'Salary', description: 'Monthly Salary from Globex Corporation', amount: 2850.00 },
      { date: '2023-08-11', category: 'Interest', description: 'Bond Interest Payment', amount: 45.00 },
      { date: '2023-08-19', category: 'Property', description: 'Commercial Property Lease', amount: 2200.00 },
      { date: '2023-08-27', category: 'Others', description: 'Consulting Services', amount: 600.00 },
      
      // September Income
      { date: '2023-09-05', category: 'Salary', description: 'Monthly Salary from Shopify', amount: 3100.00 },
      { date: '2023-09-12', category: 'Interest', description: 'Savings Account Interest', amount: 32.00 },
      { date: '2023-09-18', category: 'Property', description: 'Storage Unit Rental', amount: 250.00 },
      { date: '2023-09-24', category: 'Others', description: 'Freelance Writing', amount: 450.00 },

      // October Income
      { date: '2023-10-05', category: 'Salary', description: 'Monthly Salary from Sun Life', amount: 2950.00 },
      { date: '2023-10-11', category: 'Interest', description: 'Investment Account Interest', amount: 38.00 },
      { date: '2023-10-17', category: 'Property', description: 'Airbnb Property Income', amount: 1300.00 },
      { date: '2023-10-23', category: 'Others', description: 'Graphic Design Work', amount: 400.00 },

      // November Income
      { date: '2023-11-05', category: 'Salary', description: 'Monthly Salary from Manulife', amount: 2800.00 },
      { date: '2023-11-12', category: 'Interest', description: 'GIC Interest', amount: 45.00 },
      { date: '2023-11-18', category: 'Property', description: 'Cottage Rental Income', amount: 1200.00 },
      { date: '2023-11-25', category: 'Others', description: 'Art Sale Earnings', amount: 350.00 },

      // December Income
      { date: '2023-12-02', category: 'Property', description: 'Cottage Rental Income', amount: 1200.00 },
      { date: '2023-12-02', category: 'Others', description: 'Youtube Adsense', amount: 45.00 },
      { date: '2023-12-03', category: 'Interest', description: 'WealthSimple Bonus', amount: 12.00 },
      { date: '2023-12-03', category: 'Salary', description: 'Monthly Salary from Manulife', amount: 1095.00 },
    ].map(i => ({ ...i, type: 'income' })),
    
    budgets: {
      '2023-08': 300, // Budget for August
      '2023-09': 700, // Budget for September
      '2023-10': 1000, // Budget for October
  },
};

